# Parameters that require personalization -----
proj_name: your_project_name

# QIIME2 container to use
singularity_image: "/netscratch/dep_psl/common/singularity_sifs/qiime-2026.1.sif"

#Uncomment the lines with the primer sequences used to generate the amplicon library.
# cutadapt: primer trimming. 
# B3 (341F-806R)
# primerF: CCTACGGGAGGCAGCAG
# primerR: GGACTACHVGGGTWTCTAAT 
# B5 (799F-1192R)
primerF: AACMGGATTAGATACCC
primerR: ACGTCATCCCCACCTTCC

# Optional parameters -----
# Subsample flags. Define which fraction (default: 100%) of the reads to process. Modify if you want to run a portion only.
pct: 100
# cutadapt: demux - error rate
# Set to 0 to allow 0 errors, 0.1 (default) to allow 1 error, 0.17 for 2 errors when matching to the barcode
cutadapt_error_rate: 0

# From this point on, do not change unless you know what you are doing ----

# snakemake parameters -----
input_dir: novogene_data
untrimmed_raw_data: untrimmed_raw_data
raw_data: raw_data
mappingfile: metadata/mapping.txt
scratch: scratch
outputDIR: Results

# cutadapt parameters -----
# cutadapt: primer trimming parameters
primer_err: 0.25
primer_overlap: 10

#cutadapt: demux
# how many bp need to be cut from the reads (we remove 2 bp, AC)
barcode_cut: 2 
# useful when one has lots of samples, higher values might not be necessarily better
cutadapt_cores: 32
# If you have more than 96 samples setting cutadapt_batch to a value like 25, may solve "too many files" errors related to sample quantity. 
cutadapt_batch: 25

# QIIME2-specific flags -----
# Defaults for amplicon tag-sequencing - uncomment only parameters you need.

#Qiime2 parameters
# threads for qiime2 steps
q2_cores: 32
# classifier to use for 16S, B5 primers
# Adapt accordingly if you want to use another fragment
qiime_classifier: /netscratch/dep_psl/common/qiime_classifiers/classifier_2026.1_V5V7-classifier.qza

# DADA2: denoising parameters
# truncation lengths
# Positions where reads should be truncated based on quality profiles
# guideline: check the median quality scores of your reds
# if the quality drops below 20-25 at a certain position consider truncating there
# there must be overlap between forward and reverse reads after truncation (at least 12 bp)
trunc_len_f: 0
trunc_len_r: 0
# maximum expected errors (moderate, default values)
# do not change unless you know what you are doing
# e.g. if reverse reads have borderline quality you might want to relax max_ee_r (e.g. to 3.0)
# if truncation would break the overlap
# this way you retain more reads, however you might also introduce more errors
max_ee_f: 2.0
max_ee_r: 2.0